"use strict";
exports.__esModule = true;
var ListaDeAnimales_1 = require("./ListaDeAnimales");
var Ara_a_1 = require("./Ara\u00F1a");
var Pez_1 = require("./Pez");
var Gato_1 = require("./Gato");
var gato01 = new Gato_1.Gato(4);
var pez01 = new Pez_1.Pez(6);
var araña01 = new Ara_a_1.Araña(8);
var pez02 = new Pez_1.Pez(2);
var ListaAnimales01 = new ListaDeAnimales_1.ListaDeAnimales([]);
ListaAnimales01.agregarAnimal(pez01);
ListaAnimales01.agregarAnimal(gato01);
console.log(ListaAnimales01);
console.log(ListaAnimales01.buscar(gato01));
console.log(ListaAnimales01.buscar(araña01));
console.log(ListaAnimales01);
ListaAnimales01.removerAnimal(gato01);
console.log(ListaAnimales01);
